from datetime import datetime

SEVERITY_EMOJI = {
    "ERROR": "🔴",
    "WARNING": "🟡",
    "INFO": "🔵",
    "CRITICAL": "🔴",
    "HIGH": "🔴",
    "MEDIUM": "🟡",
    "LOW": "🔵",
}

def save_report(output_path: str, repo_name: str, repo_url: str, findings: dict, ai_summary: str | None):
    """Generate and save the final Markdown report."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    semgrep = findings.get("semgrep", [])
    deps = findings.get("dependencies", [])
    secrets = findings.get("secrets", [])
    total = len(semgrep) + len(deps) + len(secrets)

    lines = []
    lines.append(f"# RepoAudit Security Report")
    lines.append(f"\n**Repository:** [{repo_name}]({repo_url})")
    lines.append(f"**Scanned:** {now}")
    lines.append(f"**Total Issues Found:** {total}")
    lines.append("\n---\n")

    # AI summary section
    if ai_summary:
        lines.append("## AI Security Analysis\n")
        lines.append(ai_summary)
        lines.append("\n---\n")

    # Static analysis
    lines.append(f"## Static Analysis ({len(semgrep)} findings)\n")
    if semgrep:
        lines.append("| Severity | File | Line | Issue |")
        lines.append("|----------|------|------|-------|")
        for f in semgrep:
            sev = f.get("severity", "WARNING")
            emoji = SEVERITY_EMOJI.get(sev, "⚪")
            rule = f.get("rule", "").split(".")[-1]
            lines.append(f"| {emoji} {sev} | `{f['file']}` | {f['line']} | {rule} |")

        lines.append("\n### Details\n")
        for f in semgrep[:20]:
            lines.append(f"**{f.get('rule', 'unknown')}** — `{f['file']}` line {f['line']}")
            lines.append(f"\n> {f.get('message', '')}\n")
            if f.get("code"):
                lines.append(f"```\n{f['code']}\n```\n")
    else:
        lines.append("_No static analysis issues found._\n")

    # Dependencies
    lines.append(f"## Vulnerable Dependencies ({len(deps)} found)\n")
    if deps:
        lines.append("| Package | Ecosystem | CVE | Fix |")
        lines.append("|---------|-----------|-----|-----|")
        for d in deps:
            fix = ", ".join(d.get("fix_versions", [])) or "Update ASAP"
            lines.append(f"| `{d['package']}` | {d.get('ecosystem','?')} | {d['cve']} | {fix} |")
    else:
        lines.append("_No vulnerable dependencies found._\n")

    # Secrets
    lines.append(f"\n## Hardcoded Secrets ({len(secrets)} found)\n")
    if secrets:
        lines.append("> ⚠️ **Rotate these credentials immediately if this repo is/was public.**\n")
        lines.append("| Type | File | Line |")
        lines.append("|------|------|------|")
        for s in secrets:
            lines.append(f"| {s['type']} | `{s['file']}` | {s['line']} |")
    else:
        lines.append("_No hardcoded secrets found._\n")

    lines.append("\n---")
    lines.append("_Generated by [RepoAudit](https://github.com/NISTALTALSON/repoaudit) — Free open source security scanner_")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))